### ISSUE TITLE
Refine terminology definitions

### ISSUE THREAD

**Issue by peatroot** [opentargets/postgap-app#37]
Here are the current terminology definitions. Should they be ammended?

| Term | Definition |
| -- | -- |
|otscore|The Open Targets G2V score is an aggregation of the VEP, GTEx, PCHiC, DHS, Fantom5 and Nearest subscores. Within [0, 1].|
|vep|The Variant Effect Predictor (VEP) score is taken as the consequence expressed on a scale from 0 to 4.|
|gtex|The GTEx score is taken as max(1 - p-value) across all tissues for the eQTL between the given target and variant. Within [0, 1].|
|pchic|The PCHiC score is taken as max normalized Promoter Capture Hi-C score (CHiCAGO output) for linked sites containing variant and target (across all tissues). Within [0, 1].|
|dhs|The DHS score is taken as (1 - false discovery rate) for linked sites (via correlated DNase hypersensitivity) containing variant and target. Within [0, 1].|
|fantom5|The Fantom5 score is taken as (1 - false discovery rate) for linked sites (miRNAs and their promoters) containing variant and target. Within [0, 1].|
|r2|The linkage disequilibrium (r2) between the lead variant and the variant.|
|gwaspvalue|The reported p-value from GWAS catalog between the lead variant and disease.|
|gwassamplesize|The reported sample size from GWAS catalog between the lead variant and disease.|
|variants|Variants from Ensembl with at least one association.|
|leadvariants|Variants identified as being associated with a disease directly through a GWAS.|
|genes|Genes from Ensembl with at least one association.|
|diseases|Diseases identified as being associated with a lead variant through a GWAS.|

**Comment by deniseOme** [comment]
Suggestions for the description:
A) The Open Targets G2V (gene to variant) score is a (mathematical or stastitical?!?!) aggregation of the VEP, GTEx, PCHiC, DHS, Fantom5 and Nearest gene scores. It varies from 0 to 1.

B) The Variant Effect Predictor (VEP) score is the functional consequence of the variant e.g. missense, transcript ablation. It can be 0, 1, 2, 3, or 4.

C) The GTEx score is the max(1 - p-value) across all tissues for the eQTL between the target and variant. It varies from 0 to 1.

D) The PCHiC score is the max normalised promoter capture Hi-C score (CHiCAGO output) across all tissues for linked sites containing variant and target. It varies from 0 to 1.

E) The DHS score equals (1 - false discovery rate) for linked sites (via correlated DNase hypersensitivity) containing variant and target. It varies from 0 to 1.

F) The Fantom5 score equals (1 - false discovery rate) for linked sites (miRNAs and their promoters) containing variant and target. It varies from 0 to 1.

G) The r2 value is the correlation between the lead variant and the variant. It varies from 0 to 1, the latter for sites are in complete linkage disequilibrium and therefore co-inherited. It comes from Ensembl.

H) The GWAS p-value is the statistical evidence against the null hypothesis that the lead variant is not associated with the disease. It's curated from papers by the GWAS catalog.

I) The GWAS sample is the reported size of cases between the lead variant and disease. It's curated from papers by the GWAS catalog.

J) Variants are SNPs and mutations with at least one association with a trait/disease. Data comes from Ensembl.

K) Lead variants are identified as being associated with a disease directly through a GWAS.

L) Genes from Ensembl with at least one association.

M) Diseases identified as being associated with a lead variant.

These are some overall comments: 

* try to be consistent throughout e.g.  use within[0,1] or scale from 0-4 but not both.

* if we spell an acronym out e.g. VEP, it would be good to do so for all other acronyms specially the more cryptic ones such as G2V. GWAS is almost a given, specially for the users of PostGap, I'd have thought.

* where can we find which functional consequences from the VEP get score of O, which are 1, 2, 3, and 4 (presumably LoF, missense variants)?

* What is a Chicago output? Could not find this on google? Shall we provide a link to this?

**Comment by peatroot** [comment]
Thanks @deniseOme, these are much improved. I think we will eventually need a page describing the methods in more detail, so we should revisit these definitions when that page exists, including the VEP consequence mapping. I believe CHiCAGO is a piece of software for analysing PCHiC output statistically, so we can include a link to this in the methods page perhaps, if one can be found.
